---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# aouFI

<!-- badges: start -->
<!-- badges: end -->

R package of helper functions for the Roux OHDSI Frailty project

## Installation

``` r
remotes::install_github("roux-ohdsi/aouFI")
```

## Functions

- `getEligible()` retrieves a single column dataframe of person_ids from the AoU database (when provided with a database connection) that are > 50 years old and < 120 years old (defaults).
- `getConcepts()` retrieves index concept_ids and names
- `omop2fi()` returns a dataframe of frailty category occurrences when given a database connection to any (in theory) OMOP CDM database and a table of person_id values (e.g., from `getEligible()`), and a frailty index (one of efi, efragicap, vafi, or hfrs). In theory, this data can be used with `getFI()` though this is not yet tested...
- `getFI()` returns frailty scores for a several FIs given a dataframe of person_id's, start, and end dates. It requires a specific data input format and isn't terribly flexible yet.

## Data

### FI Tables

These tables hold concept_ids and concept names for each of the frailty indices. They can be queried
using `getConcepts()`. Used by the `omop2fi()` function.

- efi_concepts.rda
- efragicap_concepts.rda
- hfrs_concepts.rda
- vafi_concepts.rda

Data generating scripts are either in data-raw on on the AoU workbench...

### Other useful tables

- `survey_names` List of surveys given in All of US
- `FI_labels` Paper-ready names for AouFI variables with a linking column for derived data
- `simulated_ehr` Simulated ehr data to search - similar to what would be returned by `omop2fi()`. This will be used for 
testing and demo purposes. It can be used with getFI(). The values in this data are entirely fabricated based on code in /data-raw.
Next step is to add a third dataset with occurrences that don't fall within any of the FIs as well to be able to test the omop2fi function.
- `simulated_cohort` Simulated cohort with a starting search date. Can be used with `simulated_ehr` to use the `getFI()` function. It 
contains a sample of fake participants in simulated_ehr with randomly generated start dates in the observation period for each person_id.

