# file to generate efragicap concept codes
# this will only work in AoU right now...


    combos <- tribble(
        ~disease_name, ~code_to_match,
        "Mobility & transfer problems",        "Z99.3",
        "Housebound",        "Z74.9",
        "Activity limitation",        "Z73.6",
        "Activity limitation",        "Z63.6",
        "Visual impairment",         "H25%",
        "Visual impairment",         "H26%",
        "Visual impairment",         "H28%",
        "Visual impairment",         "H40%",
        "Visual impairment",         "H42%",
        "Visual impairment",         "H53%",
        "Visual impairment",         "H54%",
        "Hearing impairment",         "H90%",
        "Hearing impairment",         "H91%",
        "Hearing impairment",        "Z46.1",
        "Hearing impairment",        "Z96.2",
        "Hearing impairment",        "Z97.4",
        "Requirement for care",        "Z59.3",
        "Social vulnerability",        "Z63.9",
        "Social vulnerability",        "Z63.2",
        "Social vulnerability",        "Z63.4",
        "Social vulnerability",        "Z60.9",
        "Social vulnerability",        "Z59.1",
        "Social vulnerability",        "Z59.6",
        "Social vulnerability",        "Z73.4",
        "Social vulnerability",        "Z73.5",
        "Social vulnerability",        "Z60.2",
        "Social vulnerability",        "Z60.4",
        "Social vulnerability",          "Z60",
        "Social vulnerability",        "Z60.%",
        "Social vulnerability",          "Z59",
        "Social vulnerability",        "Z59.0",
        "Social vulnerability",        "Z59.1",
        "Social vulnerability",        "Z59.2",
        "Social vulnerability",        "Z59.4",
        "Social vulnerability",        "Z59.5",
        "Social vulnerability",        "Z59.6",
        "Social vulnerability",        "Z59.7",
        "Social vulnerability",        "Z59.8",
        "Social vulnerability",        "Z59.9",
        "Social vulnerability",        "Z60.2",
        "Social vulnerability",       "Z73.91",
        "Social vulnerability",       "Z91.81",
        "Social vulnerability",        "Z91.2",
        "Falls",          "W0%",
        "Falls",          "W1%",
        "Falls",        "R29.6",
        "Falls",       "R26.89",
        "Urinary incontinence",          "R32",
        "Urinary incontinence",        "N39.3",
        "Urinary incontinence",        "N39.4",
        "Urinary incontinence",       "I13211",
        "Urinary incontinence",       "I13212",
        "Urinary incontinence",       "I13213",
        "Urinary incontinence",       "I13214",
        "Urinary incontinence",       "I13215",
        "Weight loss & anorexia",        "R63.0",
        "Weight loss & anorexia",        "R63.3",
        "Weight loss & anorexia",        "R63.4",
        "Weight loss & anorexia",          "R64",
        "Weight loss & anorexia",          "E46",
        "Weight loss & anorexia",         "F00%",
        "Memory & cognitive problems",         "F01%",
        "Memory & cognitive problems",         "F02%",
        "Memory & cognitive problems",         "F03%",
        "Memory & cognitive problems",        "F06.7",
        "Memory & cognitive problems",         "G30%",
        "Memory & cognitive problems",         "G31%",
        "Memory & cognitive problems",       "R41.81",
        "Memory & cognitive problems",         "I831",
        "Dizziness",         "R42%",
        "Dizziness",         "H81%",
        "Dizziness",         "H82%",
        "Dyspnoea",        "R06.0",
        "Sleep disturbance",          "F51",
        "Sleep disturbance",        "G47.0",
        "Sleep disturbance",         "I621",
        "Anaemia & haematinic deficiency",         "D46%",
        "Anaemia & haematinic deficiency",         "D50%",
        "Anaemia & haematinic deficiency",         "D51%",
        "Anaemia & haematinic deficiency",         "D52%",
        "Anaemia & haematinic deficiency",         "D53%",
        "Anaemia & haematinic deficiency",         "D55%",
        "Anaemia & haematinic deficiency",         "D56%",
        "Anaemia & haematinic deficiency",         "D57%",
        "Anaemia & haematinic deficiency",         "D58%",
        "Anaemia & haematinic deficiency",         "D59%",
        "Anaemia & haematinic deficiency",         "D60%",
        "Anaemia & haematinic deficiency",         "D61%",
        "Anaemia & haematinic deficiency",         "D62%",
        "Anaemia & haematinic deficiency",         "D63%",
        "Anaemia & haematinic deficiency",         "D64%",
        "Hypertension",          "I10",
        "Hypertension",          "I11",
        "Hypertension",        "I11.0",
        "Hypertension",        "I11.0",
        "Hypertension",          "I12",
        "Hypertension",        "I12.0",
        "Hypertension",        "I12.9",
        "Hypertension",          "I13",
        "Hypertension",        "I13.0",
        "Hypertension",        "I13.1",
        "Hypertension",        "I13.2",
        "Hypertension",        "I13.9",
        "Hypertension",          "I15",
        "Hypertension",        "I15.0",
        "Hypertension",        "I15.1",
        "Hypertension",        "I15.2",
        "Hypertension",        "I15.8",
        "Hypertension",        "I15.9",
        "Ischaemic heart disease",         "I20%",
        "Ischaemic heart disease",         "I21%",
        "Ischaemic heart disease",         "I22%",
        "Ischaemic heart disease",         "I23%",
        "Ischaemic heart disease",         "I24%",
        "Ischaemic heart disease",         "I25%",
        "Heart failure",        "I11.0",
        "Heart failure",        "I13.0",
        "Heart failure",        "I13.2",
        "Heart failure",         "I50%",
        "Cerebrovascular disease",         "G45%",
        "Cerebrovascular disease",         "G46%",
        "Cerebrovascular disease",         "I60%",
        "Cerebrovascular disease",         "I61%",
        "Cerebrovascular disease",         "I62%",
        "Cerebrovascular disease",         "I63%",
        "Cerebrovascular disease",         "I64%",
        "Cerebrovascular disease",         "I65%",
        "Cerebrovascular disease",         "I66%",
        "Cerebrovascular disease",         "I67%",
        "Cerebrovascular disease",         "I68%",
        "Cerebrovascular disease",         "I69%",
        "Cerebrovascular disease",        "S06.6",
        "Cerebrovascular disease",        "S06.5",
        "Peripheral vascular disease",         "I70%",
        "Peripheral vascular disease",          "I71",
        "Peripheral vascular disease",        "I71.2",
        "Peripheral vascular disease",        "I71.4",
        "Peripheral vascular disease",        "I71.9",
        "Peripheral vascular disease",          "I72",
        "Peripheral vascular disease",        "I72.9",
        "Peripheral vascular disease",          "I73",
        "Peripheral vascular disease",        "I73.0",
        "Peripheral vascular disease",        "I73.9",
        "Peripheral vascular disease",          "I74",
        "Peripheral vascular disease",        "I74.9",
        "Peripheral vascular disease",          "I77",
        "Peripheral vascular disease",        "I77.0",
        "Peripheral vascular disease",        "I77.6",
        "Peripheral vascular disease",        "I77.9",
        "Peripheral vascular disease",        "E10.5",
        "Peripheral vascular disease",        "E11.5",
        "Peripheral vascular disease",        "E13.5",
        "Atrial fibrillation",         "I48%",
        "Heart valve disease",         "I05%",
        "Heart valve disease",         "I06%",
        "Heart valve disease",         "I07%",
        "Heart valve disease",         "I08%",
        "Heart valve disease",         "I33%",
        "Heart valve disease",         "I34%",
        "Heart valve disease",         "I35%",
        "Heart valve disease",         "I36%",
        "Heart valve disease",         "I37%",
        "Heart valve disease",         "I38%",
        "Heart valve disease",         "I39%",
        "Hypotension/syncope",         "I95%",
        "Hypotension/syncope",          "R55",
        "Diabetes",         "E10%",
        "Diabetes",         "E11%",
        "Diabetes",         "E12%",
        "Diabetes",         "E13%",
        "Diabetes",         "E14%",
        "Diabetes",        "H36.0",
        "Diabetes",        "G59.0",
        "Diabetes",        "G63.2",
        "Diabetes",        "H28.0",
        "Diabetes",        "M14.2",
        "Diabetes",        "N08.3",
        "Diabetes",        "E08.6",
        "Foot problems",          "L84",
        "Arthritis",          "M0%",
        "Arthritis",          "M1%",
        "Arthritis",         "M42%",
        "Arthritis",         "M45%",
        "Arthritis",          "M46",
        "Arthritis",          "M47",
        "Arthritis",          "M48",
        "Arthritis",        "M77.2",
        "Arthritis",        "Z96.6",
        "Respiratory disease",         "J42%",
        "Respiratory disease",         "J43%",
        "Respiratory disease",         "J44%",
        "Respiratory disease",         "J45%",
        "Respiratory disease",          "J46",
        "Peptic ulcer",         "K25%",
        "Peptic ulcer",         "K26%",
        "Peptic ulcer",         "K27%",
        "Peptic ulcer",         "K28%",
        "Thyroid disease",         "D34%",
        "Thyroid disease",         "E01%",
        "Thyroid disease",         "E02%",
        "Thyroid disease",         "E03%",
        "Thyroid disease",         "E04%",
        "Thyroid disease",         "E05%",
        "Thyroid disease",         "E06%",
        "Thyroid disease",         "E07%",
        "Thyroid disease",        "R94.6",
        "Chronic kidney disease",         "N18%",
        "Chronic kidney disease",         "N19%",
        "Chronic kidney disease",         "Q61%",
        "Chronic kidney disease",        "E10.2",
        "Chronic kidney disease",        "E11.2",
        "Chronic kidney disease",        "E13.2",
        "Chronic kidney disease",        "E14.2",
        "Osteoporosis",         "M80%",
        "Osteoporosis",         "M81%",
        "Osteoporosis",         "M82%",
        "Fragility fracture",         "M80%",
        "Fragility fracture",         "M84%",
        "Fragility fracture",        "M48.4",
        "Fragility fracture",        "M48.5",
        "Fragility fracture",         "M9.5",
        "Fragility fracture",         "S12%",
        "Fragility fracture",         "S22%",
        "Fragility fracture",         "S32%",
        "Fragility fracture",         "S52%",
        "Fragility fracture",         "S62%",
        "Fragility fracture",         "S72%",
        "Fragility fracture",          "T08",
        "Fragility fracture",        "T08.0",
        "Fragility fracture",        "T10.0",
        "Parkinsonism & tremor",         "G20%",
        "Parkinsonism & tremor",         "G21%",
        "Parkinsonism & tremor",         "G22%",
        "Parkinsonism & tremor",         "G25%",
        "Parkinsonism & tremor",        "R25.1",
        "Urinary system disease",          "N0%",
        "Urinary system disease",           "N1",
        "Urinary system disease",          "N2%",
        "Urinary system disease",         "N30%",
        "Urinary system disease",         "N31%",
        "Urinary system disease",         "N32%",
        "Urinary system disease",         "N33%",
        "Urinary system disease",         "N34%",
        "Urinary system disease",         "N35%",
        "Urinary system disease",         "N36%",
        "Urinary system disease",         "N37%",
        "Urinary system disease",         "N38%",
        "Urinary system disease",          "N39",
        "Urinary system disease",        "N39.9",
        "Skin ulcer",        "I83.0",
        "Skin ulcer",        "I89.0",
        "Skin ulcer",          "L97"
    )



    download_data <- function(query) {
        tb <- bigrquery::bq_project_query(Sys.getenv('GOOGLE_PROJECT'), query)
        bigrquery::bq_table_download(tb)
    }

    download_combos <- function(disease_name, code_to_match, ...) {

        CDR <- Sys.getenv('WORKSPACE_CDR')

        q <- str_glue("
       SELECT CAST('{disease_name}' AS STRING) AS efi_category,
         CAST(source_code AS STRING) AS efi_icd10_code,
         target_concept_id AS efi_concept_id
       FROM (
         SELECT source.concept_code AS source_code,
           target.concept_id AS target_concept_id
         FROM `{CDR}.concept_relationship`
         INNER JOIN `{CDR}.concept` source
           ON source.concept_id = concept_id_1
         INNER JOIN `{CDR}.concept` target
           ON target.concept_id = concept_id_2
         WHERE source.vocabulary_id LIKE 'ICD10%'
           AND target.vocabulary_id = 'SNOMED'
           AND relationship_id = 'Maps to'
         ) source_to_concept_map
       WHERE source_code LIKE '{code_to_match}'
       ")

        download_data(q)
    }

    categories_concepts <- pmap_dfr(combos, download_combos) %>% distinct()

    #usethis::use_data(categories_concepts, overwrite = TRUE)

